### ISSUE TITLE
couple small issues

### ISSUE THREAD

**Issue by lookfirst** [twitvid/node-MessageBus#3]
thanks for a helpful tool. some minor feedback...

xdate doesn't really seem to help much. moment.js would probably be simpler code.

the iso8601 comments are not actually iso8601 format

the q package doesn't actually seem to be used, but maybe i missed it.

**Comment by thesmart** [comment]
Thanks for your eyeballs.  I have pushed an update.
- I've used both XDate and moment, and I disagree
- removed both XDate and Q from dependencies
- fixed the iso8601, MessageBus servers actually accept only a weird dialect of iso8601 dates without milliseconds

**Comment by lookfirst** [comment]
Sounds good. The thing I like about moment is that I've had chats with the author and it is clear he's pretty concerned with two things that are important to me: a) speed and b) having a clean api. xchat may also have the same requirements, I don't know.

Thanks for closing this so quickly. You rock.
