### ISSUE TITLE
Sending email via sendEmailMessage

### ISSUE THREAD

**Issue by ujjwal** [twitvid/node-MessageBus#4]
Trying to figure out how to pass in the parameters (options) to sendEmailMessage

client.sendEmailMessage('bob@example.com', 'noreply@example.com', 'Single Message Sample', options, function(err, resp) {

..});

What does options look like - it is just an js object?

**Comment by ujjwal** [comment]
``` javascript
MsgBusClient.prototype.sendEmailMessage = function(toEmail, fromEmail, subject, options, cb) {
    if (_.isFunction(arguments[3])) {
        cb = arguments[3];
        options = undefined;
    }

    var params = Object.create(options ? options : null);
```

I am not entirely sure what Object.create is doing here. It returns an empty hash.

**Comment by thesmart** [comment]
Options is an object.  It applies any additional parameters in the MessageBus API:
https://www.messagebus.com/documentation-content/#Sending Email

**Comment by thesmart** [comment]
```
toName (optional)   a string containing the message recipient's name
fromName (optional) a string containing the message sender's name
plaintextBody (optional)    a string containing the plaintext message body.
htmlBody (optional) a string containing the HTML message body.
customHeaders (optional)    a hash of key/value strings, where keys are custom email headers and values are appropriate to each message recipient
sessionKey (optional)   a GUID identifying the session to associate the message to and corresponding statistics. If a key is not provided, the message will be given a default key (default key alias is "DEFAULT")
```

**Comment by thesmart** [comment]
In hindsight, I would have made the client a chain-able pattern instead of using optional arguments.  For example:

``` javascript
var client = new MessageBusClient(apiKey);
client.createEmail(toEmail)
    .setFromName('John')
    .setFromEmail('foo@messagebus.com')
    .setHtml(htmlContent)
    .send(function(err, result) {
        if (err) throw err;
        console.info(result);
    });
```

**Comment by ujjwal** [comment]
``` javascript
client.sendEmailMessage('bob@example.com', 'noreply@example.com', 
'Single Message Sample', 
{ plaintextBody: 'test body'}, 
function(err, resp) {
    console.log("Response :", resp);
});
```

This doesn't work for me, maybe I am missing something.  I do like the chain-able pattern but it doesn't differentiate between required and optional parameters. The options object isn't getting passed through to the POST. I am adding a test case for this scenario.

**Comment by thesmart** [comment]
Wow, you're right -- pretty bad bug.  Batch endpoint works

**Comment by thesmart** [comment]
Does this fix the issue for you? The code is in branch "ujjwal@client.sendEmailMessage"

https://github.com/twitvid/node-MessageBus/pull/5
